import React, { useEffect, useState } from "react";
import Navbar from "@/components/Navbar";
import { BsArrowUpSquare } from "react-icons/bs";
import Head from "next/head";
import Leanding from "@/components/Leading";
import About from "@/components/About";
import Skils from "@/components/Skils";

export default function Home() {
  // Back To Top
  const [showButton, setShowButton] = useState(false);
  useEffect(() => {
    window.addEventListener("scroll", () => {
      if (window.pageYOffset > 300) {
        setShowButton(true);
      } else {
        setShowButton(false);
      }
    });
  }, []);

  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth", // for smoothly scrolling
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="scroll-smooth flex justify-center items-center pb-10">
        <Navbar />
        <div className="container w-full px-4">
          <React.Fragment>
            <Leanding />
            <About />
            <Skils />
          </React.Fragment>
        </div>

        {showButton && (
          <button className="text-3xl fixed bottom-12 right-12 p-2 bg-white shadow-md animate-bounce rounded-md" onClick={() => scrollToTop()}>
            <BsArrowUpSquare className="text-slate-500" />
          </button>
        )}
      </main>
    </>
  );
}
